DROP DATABASE IF EXISTS employee_directory_project;
CREATE DATABASE employee_directory_project;
USE employee_directory_project;

CREATE TABLE employee (
	id BIGINT AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	department ENUM('HR', 'IT', 'FINANCE', 'OPERATIONS') NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME,
	is_deleted BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (id)
);

CREATE TABLE `user` (
	employee_id BIGINT NOT NULL,
	username VARCHAR(15) NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME,
	last_login DATETIME,
	deleted_at DATETIME,
	is_deleted BOOLEAN DEFAULT FALSE,
	role ENUM('ADMIN') NOT NULL,
	PRIMARY KEY (employee_id),
	FOREIGN KEY (employee_id) REFERENCES employee(id)
);

DESC employee;
DESC `user`;

INSERT INTO employee (name, email, department) VALUES
('Sathish Shan', 'shansathish38@gmail.com', 'IT'),
('Sahan Perera', 'sahan.perera@example.com', 'IT'),
('Nimesha Fernando', 'nimesha.fernando@example.com', 'HR'),
('Tharindu Silva', 'tharindu.silva@example.com', 'FINANCE'),
('Ishara Jayasinghe', 'ishara.jaya@example.com', 'OPERATIONS'),
('Dilani Wickramasinghe', 'dilani.wick@example.com', 'IT'),
('Kasun De Silva', 'kasun.desilva@example.com', 'IT'),
('Nadeesha Bandara', 'nadeesha.bandara@example.com', 'HR'),
('Janith Kumara', 'janith.kumara@example.com', 'OPERATIONS'),
('Thilini Wijesinghe', 'thilini.wijesinghe@example.com', 'FINANCE'),
('Chamath Perera', 'chamath.perera@example.com', 'IT'),
('Rashmi Gunawardena', 'rashmi.gunawardena@example.com', 'HR'),
('Ishan Madushanka', 'ishan.madushanka@example.com', 'OPERATIONS'),
('Dinithi Herath', 'dinithi.herath@example.com', 'IT'),
('Prabodha Jayasekara', 'prabodha.jayasekara@example.com', 'FINANCE'),
('Kavindu Ranasinghe', 'kavindu.ranasinghe@example.com', 'IT'),
('Hiruni Rajapaksha', 'hiruni.rajapaksha@example.com', 'HR'),
('Sajith Abeykoon', 'sajith.abeykoon@example.com', 'OPERATIONS'),
('Sachini Amarasinghe', 'sachini.amarasinghe@example.com', 'FINANCE'),
('Thimira Weerasinghe', 'thimira.weerasinghe@example.com', 'IT'),
('Udani Senanayake', 'udani.senanayake@example.com', 'HR'),
('Malith Dissanayake', 'malith.dissanayake@example.com', 'OPERATIONS'),
('Sanduni Rathnayake', 'sanduni.rathnayake@example.com', 'FINANCE'),
('Lasith Jayawardena', 'lasith.jayawardena@example.com', 'IT'),
('Harshani Ekanayake', 'harshani.ekanayake@example.com', 'HR'),
('Dulaj Karunaratne', 'dulaj.karunaratne@example.com', 'OPERATIONS'),
('Shanilka Wijeratne', 'shanilka.wijeratne@example.com', 'FINANCE'),
('Isuru Rathnayaka', 'isuru.rathnayaka@example.com', 'IT'),
('Nilakshi Senarathne', 'nilakshi.senarathne@example.com', 'HR'),
('Dinesh Perera', 'dinesh.perera@example.com', 'OPERATIONS'),
('Pavithra Dilhani', 'pavithra.dilhani@example.com', 'FINANCE'),
('Sewwandi Gamage', 'sewwandi.gamage@example.com', 'IT'),
('Himesh Jayalath', 'himesh.jayalath@example.com', 'HR'),
('Kumari Pathirana', 'kumari.pathirana@example.com', 'OPERATIONS'),
('Thisara Alwis', 'thisara.alwis@example.com', 'FINANCE'),
('Sachintha Herath', 'sachintha.herath@example.com', 'IT'),
('Nirasha Weerasekara', 'nirasha.weerasekara@example.com', 'HR'),
('Charith Ekanayake', 'charith.ekanayake@example.com', 'OPERATIONS'),
('Dilki Fernando', 'dilki.fernando@example.com', 'FINANCE'),
('Pubudu Samarasinghe', 'pubudu.samarasinghe@example.com', 'IT'),
('Anushka Tennakoon', 'anushka.tennakoon@example.com', 'HR'),
('Sewmini Maduranga', 'sewmini.maduranga@example.com', 'OPERATIONS'),
('Lakshan Wickrama', 'lakshan.wickrama@example.com', 'FINANCE'),
('Thamali Dias', 'thamali.dias@example.com', 'IT'),
('Ravindu Nirmal', 'ravindu.nirmal@example.com', 'HR'),
('Chathurika Sandamali', 'chathurika.sandamali@example.com', 'OPERATIONS'),
('Kavisha Thilakarathna', 'kavisha.thilakarathna@example.com', 'FINANCE'),
('Senuri Hansika', 'senuri.hansika@example.com', 'IT'),
('Mahesha Perera', 'mahesha.perera@example.com', 'HR'),
('Sadev Bandara', 'sadev.bandara@example.com', 'OPERATIONS'),
('Mevan Samarawickrama', 'mevan.samarawickrama@example.com', 'FINANCE'),
('Disni Rajapakse', 'disni.rajapakse@example.com', 'IT'),
('Hirushan Fernando', 'hirushan.fernando@example.com', 'HR'),
('Yasith Hettiarachchi', 'yasith.hettiarachchi@example.com', 'OPERATIONS'),
('Dananjaya Ranatunga', 'dananjaya.ranatunga@example.com', 'FINANCE'),
('Sandali Athukorala', 'sandali.athukorala@example.com', 'IT'),
('Ashen Jayasuriya', 'ashen.jayasuriya@example.com', 'HR'),
('Vihanga Mihiranga', 'vihanga.mihiranga@example.com', 'OPERATIONS'),
('Chalani Gunasekara', 'chalani.gunasekara@example.com', 'FINANCE'),
('Yohan Dias', 'yohan.dias@example.com', 'IT'),
('Nuwani Bandaranayake', 'nuwani.bandaranayake@example.com', 'HR'),
('Iresha Rajakaruna', 'iresha.rajakaruna@example.com', 'OPERATIONS'),
('Viraj Rathnayaka', 'viraj.rathnayaka@example.com', 'FINANCE'),
('Tharushi Ekanayake', 'tharushi.ekanayake@example.com', 'IT'),
('Dinara Madushani', 'dinara.madushani@example.com', 'HR'),
('Lahiru Senevirathna', 'lahiru.senevirathna@example.com', 'OPERATIONS'),
('Manuja Kalubowila', 'manuja.kalubowila@example.com', 'FINANCE'),
('Bhashini Alahakoon', 'bhashini.alahakoon@example.com', 'IT'),
('Rashmika Gunathilake', 'rashmika.gunathilake@example.com', 'HR'),
('Tharuka Jayawardane', 'tharuka.jayawardane@example.com', 'OPERATIONS'),
('Sewmini Gunarathna', 'sewmini.gunarathna@example.com', 'FINANCE'),
('Shehan Malshan', 'shehan.malshan@example.com', 'IT'),
('Anudi Dissanayaka', 'anudi.dissanayaka@example.com', 'HR'),
('Dineth Fernando', 'dineth.fernando@example.com', 'OPERATIONS'),
('Ishanka Pathirage', 'ishanka.pathirage@example.com', 'FINANCE'),
('Sajani Herath', 'sajani.herath@example.com', 'IT'),
('Harini Dias', 'harini.dias@example.com', 'HR'),
('Yasiru Hettiarachchi', 'yasiru.hettiarachchi@example.com', 'OPERATIONS'),
('Hashini Jayalath', 'hashini.jayalath@example.com', 'FINANCE'),
('Dumindu Wickramanayake', 'dumindu.wickramanayake@example.com', 'IT'),
('Nimasha Peiris', 'nimasha.peiris@example.com', 'HR'),
('Isuri Senanayake', 'isuri.senanayake@example.com', 'OPERATIONS'),
('Chirantha Alwis', 'chirantha.alwis@example.com', 'FINANCE'),
('Nirosha Karunathilake', 'nirosha.karunathilake@example.com', 'IT'),
('Sasindu Jayasundara', 'sasindu.jayasundara@example.com', 'HR'),
('Thanura Rajapaksha', 'thanura.rajapaksha@example.com', 'OPERATIONS'),
('Dulanja Samarasekara', 'dulanja.samarasekara@example.com', 'FINANCE'),
('Tashya Weerakkody', 'tashya.weerakkody@example.com', 'IT'),
('Vidhushi Karunadasa', 'vidhushi.karunadasa@example.com', 'HR'),
('Ravini Prabodha', 'ravini.prabodha@example.com', 'OPERATIONS'),
('Pasindu Ekanayaka', 'pasindu.ekanayaka@example.com', 'FINANCE');

INSERT INTO `user` (employee_id, username, password, role)
VALUES
(1, 'god_xero', '$2a$12$m8klimGVexhjMpucFB0UFOxnnaiWXFf26BH9rk/ZVaxa/RwblMAva', 'ADMIN'),
(2, 'sahan_p', '$2a$12$m8klimGVexhjMpucFB0UFOxnnaiWXFf26BH9rk/ZVaxa/RwblMAva', 'ADMIN'),
(3, 'nimesha_f', '$2a$12$m8klimGVexhjMpucFB0UFOxnnaiWXFf26BH9rk/ZVaxa/RwblMAva', 'ADMIN'),
(4, 'tharindu_s', '$2a$12$m8klimGVexhjMpucFB0UFOxnnaiWXFf26BH9rk/ZVaxa/RwblMAva', 'ADMIN'),
(5, 'ishara_j', '$2a$12$m8klimGVexhjMpucFB0UFOxnnaiWXFf26BH9rk/ZVaxa/RwblMAva', 'ADMIN');

SELECT * FROM employee;
SELECT * FROM `user`;
