server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null

  output:
    ansi:
      enabled: ALWAYS

  db:
    username: xxx
    password: xxx
    database: xxx

  security:
    user:
      name: xxx
      password: xxx  # bcrypt hash

  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx@gmail.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  from: xxx@gmail.com

jwt:
  secret: xxx
  lifetime: 10800000
  key_gen:
    enable: false
